In [32]:
import numpy as np
import pandas as pd
#from tensorflow.keras import backend
from keras import backend

In [33]:
datawith = pd.read_csv('with.csv')
datawith.loc[datawith['Married']=="Yes",'Married']=1
datawith.loc[datawith['Married']=='No','Married']=0
datawith.loc[datawith['Education']=="Graduate",'Education']=1
datawith.loc[datawith['Education']=='Not Graduate','Education']=0
datawith.loc[datawith['Self_Employed']=="Yes",'Self_Employed']=1
datawith.loc[datawith['Self_Employed']=='No','Self_Employed']=0
datawith.loc[datawith['Property_Area']=="Urban",'Property_Area']=0
datawith.loc[datawith['Property_Area']=='Semiurban','Property_Area']=1
datawith.loc[datawith['Property_Area']=='Rural', 'Property_Area']=2
datawith.head()

,Unnamed: 0,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,0,0,0,1,0,5849,0.0,146.412162,360.0,1.0,0,1
1,1,1,1,1,0,4583,1508.0,128.000000,360.0,1.0,2,0
2,2,1,0,1,1,3000,0.0,66.000000,360.0,1.0,0,1
3,3,1,0,0,0,2583,2358.0,120.000000,360.0,1.0,0,1
4,4,0,0,1,0,6000,0.0,141.000000,360.0,1.0,0,1

In [34]:
datawo = pd.read_csv('without.csv')
datawo.loc[datawo['Married']=="Yes",'Married']=1
datawo.loc[datawo['Married']=='No','Married']=0
datawo.loc[datawo['Education']=="Graduate",'Education']=1
datawo.loc[datawo['Education']=='Not Graduate','Education']=0
datawo.loc[datawo['Self_Employed']=="Yes",'Self_Employed']=1
datawo.loc[datawo['Self_Employed']=='No','Self_Employed']=0
datawo.loc[datawo['Property_Area']=="Urban",'Property_Area']=0
datawo.loc[datawo['Property_Area']=='Semiurban','Property_Area']=1
datawo.loc[datawo['Property_Area']=='Rural', 'Property_Area']=2
datawo.head()

,Unnamed: 0,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,333,1,0,1,0,63337,0.0,490.0,180,1,0,1
1,171,1,3,1,0,51763,0.0,700.0,300,1,0,1
2,155,1,3,1,0,39999,0.0,600.0,180,0,1,1
3,185,1,0,1,1,39147,4750.0,120.0,360,1,1,1
4,443,0,1,1,0,37719,0.0,152.0,360,1,1,1

In [35]:
X1 = datawith.drop("Loan_Status", axis=1)
y1 = datawith["Loan_Status"]
print(X1.shape, y1.shape)

(614, 11) (614,)

In [36]:
X2 = datawo.drop("Loan_Status", axis=1)
y2 = datawo["Loan_Status"]
print(X2.shape, y2.shape)

(599, 11) (599,)

In [37]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical

X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, random_state=1, stratify=y1)
X1_scaler = StandardScaler().fit(X1_train)
X1_train_scaled = X1_scaler.transform(X1_train)
X1_test_scaled = X1_scaler.transform(X1_test)


# Step 1: Label-encode data set
label1_encoder = LabelEncoder()
label1_encoder.fit(y1_train)
encoded_y1_train = label1_encoder.transform(y1_train)
encoded_y1_test = label1_encoder.transform(y1_test)

# Step 2: Convert encoded labels to one-hot-encoding
y1_train_categorical = to_categorical(encoded_y1_train)
y1_test_categorical = to_categorical(encoded_y1_test)

In [38]:
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, random_state=1, stratify=y2)
X2_scaler = StandardScaler().fit(X2_train)
X2_train_scaled = X2_scaler.transform(X2_train)
X2_test_scaled = X2_scaler.transform(X2_test)


# Step 1: Label-encode data set
label2_encoder = LabelEncoder()
label2_encoder.fit(y2_train)
encoded_y2_train = label2_encoder.transform(y2_train)
encoded_y2_test = label2_encoder.transform(y2_test)

# Step 2: Convert encoded labels to one-hot-encoding
y2_train_categorical = to_categorical(encoded_y2_train)
y2_test_categorical = to_categorical(encoded_y2_test)

In [39]:
#from tensorflow.keras.models import load_model
from keras.models import load_model

from keras.models import Sequential
from keras.layers import Dense
#from tensorflow.keras import backend
from keras import backend




model1 = Sequential()
model1.add(Dense(units=100, activation='relu', input_dim=11))
model1.add(Dense(units=100, activation='relu'))
model1.add(Dense(units=2, activation='softmax'))

model2 = Sequential()
model2.add(Dense(units=100, activation='relu', input_dim=11))
model2.add(Dense(units=100, activation='relu'))
model2.add(Dense(units=2, activation='softmax'))

In [40]:
model1.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])
model1.fit(
    X1_train_scaled,
    y1_train_categorical,
    epochs=100,
    shuffle=True,
    verbose=2
)

Epoch 1/100
 - 0s - loss: 0.6127 - acc: 0.7217
Epoch 2/100
 - 0s - loss: 0.4920 - acc: 0.8283
Epoch 3/100
 - 0s - loss: 0.4459 - acc: 0.8261
Epoch 4/100
 - 0s - loss: 0.4270 - acc: 0.8261
Epoch 5/100
 - 0s - loss: 0.4143 - acc: 0.8326
Epoch 6/100
 - 0s - loss: 0.4033 - acc: 0.8283
Epoch 7/100
 - 0s - loss: 0.3934 - acc: 0.8370
Epoch 8/100
 - 0s - loss: 0.3815 - acc: 0.8348
Epoch 9/100
 - 0s - loss: 0.3705 - acc: 0.8413
Epoch 10/100
 - 0s - loss: 0.3646 - acc: 0.8413
Epoch 11/100
 - 0s - loss: 0.3584 - acc: 0.8478
Epoch 12/100
 - 0s - loss: 0.3497 - acc: 0.8500
Epoch 13/100
 - 0s - loss: 0.3417 - acc: 0.8543
Epoch 14/100
 - 0s - loss: 0.3377 - acc: 0.8565
Epoch 15/100
 - 0s - loss: 0.3313 - acc: 0.8587
Epoch 16/100
 - 0s - loss: 0.3260 - acc: 0.8696
Epoch 17/100
 - 0s - loss: 0.3189 - acc: 0.8587
Epoch 18/100
 - 0s - loss: 0.3150 - acc: 0.8630
Epoch 19/100
 - 0s - loss: 0.3064 - acc: 0.8739
Epoch 20/100
 - 0s - loss: 0.2999 - acc: 0.8783
Epoch 21/100
 - 0s - loss: 0.2952 - acc: 0.8717
Epoch 22/100
 - 0s - loss: 0.2985 - acc: 0.8783
Epoch 23/100
 - 0s - loss: 0.2865 - acc: 0.8761
Epoch 24/100
 - 0s - loss: 0.2902 - acc: 0.8826
Epoch 25/100
 - 0s - loss: 0.2790 - acc: 0.8783
Epoch 26/100
 - 0s - loss: 0.2736 - acc: 0.8978
Epoch 27/100
 - 0s - loss: 0.2688 - acc: 0.8935
Epoch 28/100
 - 0s - loss: 0.2636 - acc: 0.8978
Epoch 29/100
 - 0s - loss: 0.2560 - acc: 0.8935
Epoch 30/100
 - 0s - loss: 0.2514 - acc: 0.8957
Epoch 31/100
 - 0s - loss: 0.2551 - acc: 0.9000
Epoch 32/100
 - 0s - loss: 0.2475 - acc: 0.9000
Epoch 33/100
 - 0s - loss: 0.2424 - acc: 0.8978
Epoch 34/100
 - 0s - loss: 0.2339 - acc: 0.9022
Epoch 35/100
 - 0s - loss: 0.2324 - acc: 0.9043
Epoch 36/100
 - 0s - loss: 0.2265 - acc: 0.9174
Epoch 37/100
 - 0s - loss: 0.2226 - acc: 0.9087
Epoch 38/100
 - 0s - loss: 0.2214 - acc: 0.9196
Epoch 39/100
 - 0s - loss: 0.2201 - acc: 0.9065
Epoch 40/100
 - 0s - loss: 0.2115 - acc: 0.9174
Epoch 41/100
 - 0s - loss: 0.2109 - acc: 0.9196
Epoch 42/100
 - 0s - loss: 0.2071 - acc: 0.9217
Epoch 43/100
 - 0s - loss: 0.2029 - acc: 0.9152
Epoch 44/100
 - 0s - loss: 0.2025 - acc: 0.9261
Epoch 45/100
 - 0s - loss: 0.1974 - acc: 0.9217
Epoch 46/100
 - 0s - loss: 0.1939 - acc: 0.9239
Epoch 47/100
 - 0s - loss: 0.1931 - acc: 0.9239
Epoch 48/100
 - 0s - loss: 0.1911 - acc: 0.9261
Epoch 49/100
 - 0s - loss: 0.1881 - acc: 0.9326
Epoch 50/100
 - 0s - loss: 0.1791 - acc: 0.9304
Epoch 51/100
 - 0s - loss: 0.1749 - acc: 0.9370
Epoch 52/100
 - 0s - loss: 0.1695 - acc: 0.9435
Epoch 53/100
 - 0s - loss: 0.1696 - acc: 0.9500
Epoch 54/100
 - 0s - loss: 0.1711 - acc: 0.9413
Epoch 55/100
 - 0s - loss: 0.1617 - acc: 0.9348
Epoch 56/100
 - 0s - loss: 0.1591 - acc: 0.9391
Epoch 57/100
 - 0s - loss: 0.1588 - acc: 0.9500
Epoch 58/100
 - 0s - loss: 0.1559 - acc: 0.9478
Epoch 59/100
 - 0s - loss: 0.1483 - acc: 0.9457
Epoch 60/100
 - 0s - loss: 0.1463 - acc: 0.9543
Epoch 61/100
 - 0s - loss: 0.1427 - acc: 0.9478
Epoch 62/100
 - 0s - loss: 0.1423 - acc: 0.9565
Epoch 63/100
 - 0s - loss: 0.1394 - acc: 0.9500
Epoch 64/100
 - 0s - loss: 0.1394 - acc: 0.9543
Epoch 65/100
 - 0s - loss: 0.1329 - acc: 0.9630
Epoch 66/100
 - 0s - loss: 0.1320 - acc: 0.9435
Epoch 67/100
 - 0s - loss: 0.1279 - acc: 0.9630
Epoch 68/100
 - 0s - loss: 0.1312 - acc: 0.9500
Epoch 69/100
 - 0s - loss: 0.1270 - acc: 0.9543
Epoch 70/100
 - 0s - loss: 0.1215 - acc: 0.9630
Epoch 71/100
 - 0s - loss: 0.1158 - acc: 0.9609
Epoch 72/100
 - 0s - loss: 0.1140 - acc: 0.9565
Epoch 73/100
 - 0s - loss: 0.1105 - acc: 0.9674
Epoch 74/100
 - 0s - loss: 0.1095 - acc: 0.9739
Epoch 75/100
 - 0s - loss: 0.1104 - acc: 0.9696
Epoch 76/100
 - 0s - loss: 0.1085 - acc: 0.9674
Epoch 77/100
 - 0s - loss: 0.1047 - acc: 0.9739
Epoch 78/100
 - 0s - loss: 0.1039 - acc: 0.9761
Epoch 79/100
 - 0s - loss: 0.1105 - acc: 0.9630
Epoch 80/100
 - 0s - loss: 0.1012 - acc: 0.9609
Epoch 81/100
 - 0s - loss: 0.0998 - acc: 0.9761
Epoch 82/100
 - 0s - loss: 0.0940 - acc: 0.9717
Epoch 83/100
 - 0s - loss: 0.0935 - acc: 0.9739
Epoch 84/100
 - 0s - loss: 0.0951 - acc: 0.9739
Epoch 85/100
 - 0s - loss: 0.0955 - acc: 0.9783
Epoch 86/100
 - 0s - loss: 0.0880 - acc: 0.9783
Epoch 87/100
 - 0s - loss: 0.0875 - acc: 0.9674
Epoch 88/100
 - 0s - loss: 0.0868 - acc: 0.9848
Epoch 89/100
 - 0s - loss: 0.0827 - acc: 0.9804
Epoch 90/100
 - 0s - loss: 0.0768 - acc: 0.9848
Epoch 91/100
 - 0s - loss: 0.0779 - acc: 0.9848
Epoch 92/100
 - 0s - loss: 0.0747 - acc: 0.9826
Epoch 93/100
 - 0s - loss: 0.0790 - acc: 0.9804
Epoch 94/100
 - 0s - loss: 0.0764 - acc: 0.9783
Epoch 95/100
 - 0s - loss: 0.0762 - acc: 0.9848
Epoch 96/100
 - 0s - loss: 0.0703 - acc: 0.9870
Epoch 97/100
 - 0s - loss: 0.0674 - acc: 0.9870
Epoch 98/100
 - 0s - loss: 0.0766 - acc: 0.9783
Epoch 99/100
 - 0s - loss: 0.0729 - acc: 0.9804
Epoch 100/100
 - 0s - loss: 0.0689 - acc: 0.9826

In [41]:
model2.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])
model2.fit(
    X2_train_scaled,
    y2_train_categorical,
    epochs=100,
    shuffle=True,
    verbose=2
)

Epoch 1/100
 - 0s - loss: 0.5995 - acc: 0.6882
Epoch 2/100
 - 0s - loss: 0.4729 - acc: 0.8241
Epoch 3/100
 - 0s - loss: 0.4209 - acc: 0.8486
Epoch 4/100
 - 0s - loss: 0.4032 - acc: 0.8463
Epoch 5/100
 - 0s - loss: 0.3966 - acc: 0.8441
Epoch 6/100
 - 0s - loss: 0.3890 - acc: 0.8463
Epoch 7/100
 - 0s - loss: 0.3897 - acc: 0.8486
Epoch 8/100
 - 0s - loss: 0.3881 - acc: 0.8441
Epoch 9/100
 - 0s - loss: 0.3788 - acc: 0.8419
Epoch 10/100
 - 0s - loss: 0.3683 - acc: 0.8508
Epoch 11/100
 - 0s - loss: 0.3615 - acc: 0.8530
Epoch 12/100
 - 0s - loss: 0.3563 - acc: 0.8530
Epoch 13/100
 - 0s - loss: 0.3519 - acc: 0.8530
Epoch 14/100
 - 0s - loss: 0.3480 - acc: 0.8552
Epoch 15/100
 - 0s - loss: 0.3420 - acc: 0.8530
Epoch 16/100
 - 0s - loss: 0.3373 - acc: 0.8530
Epoch 17/100
 - 0s - loss: 0.3301 - acc: 0.8575
Epoch 18/100
 - 0s - loss: 0.3290 - acc: 0.8552
Epoch 19/100
 - 0s - loss: 0.3220 - acc: 0.8552
Epoch 20/100
 - 0s - loss: 0.3188 - acc: 0.8619
Epoch 21/100
 - 0s - loss: 0.3119 - acc: 0.8619
Epoch 22/100
 - 0s - loss: 0.3091 - acc: 0.8597
Epoch 23/100
 - 0s - loss: 0.3107 - acc: 0.8575
Epoch 24/100
 - 0s - loss: 0.3048 - acc: 0.8664
Epoch 25/100
 - 0s - loss: 0.2962 - acc: 0.8597
Epoch 26/100
 - 0s - loss: 0.2887 - acc: 0.8753
Epoch 27/100
 - 0s - loss: 0.2970 - acc: 0.8753
Epoch 28/100
 - 0s - loss: 0.2892 - acc: 0.8708
Epoch 29/100
 - 0s - loss: 0.2801 - acc: 0.8864
Epoch 30/100
 - 0s - loss: 0.2906 - acc: 0.8731
Epoch 31/100
 - 0s - loss: 0.2841 - acc: 0.8820
Epoch 32/100
 - 0s - loss: 0.2742 - acc: 0.8753
Epoch 33/100
 - 0s - loss: 0.2693 - acc: 0.8797
Epoch 34/100
 - 0s - loss: 0.2649 - acc: 0.8797
Epoch 35/100
 - 0s - loss: 0.2569 - acc: 0.8886
Epoch 36/100
 - 0s - loss: 0.2511 - acc: 0.8909
Epoch 37/100
 - 0s - loss: 0.2455 - acc: 0.8931
Epoch 38/100
 - 0s - loss: 0.2434 - acc: 0.8976
Epoch 39/100
 - 0s - loss: 0.2423 - acc: 0.8909
Epoch 40/100
 - 0s - loss: 0.2382 - acc: 0.9020
Epoch 41/100
 - 0s - loss: 0.2300 - acc: 0.9087
Epoch 42/100
 - 0s - loss: 0.2294 - acc: 0.9020
Epoch 43/100
 - 0s - loss: 0.2223 - acc: 0.9109
Epoch 44/100
 - 0s - loss: 0.2203 - acc: 0.8931
Epoch 45/100
 - 0s - loss: 0.2160 - acc: 0.9176
Epoch 46/100
 - 0s - loss: 0.2163 - acc: 0.9176
Epoch 47/100
 - 0s - loss: 0.2085 - acc: 0.9198
Epoch 48/100
 - 0s - loss: 0.2053 - acc: 0.9198
Epoch 49/100
 - 0s - loss: 0.2009 - acc: 0.9220
Epoch 50/100
 - 0s - loss: 0.1973 - acc: 0.9354
Epoch 51/100
 - 0s - loss: 0.1917 - acc: 0.9287
Epoch 52/100
 - 0s - loss: 0.1902 - acc: 0.9376
Epoch 53/100
 - 0s - loss: 0.1874 - acc: 0.9243
Epoch 54/100
 - 0s - loss: 0.1955 - acc: 0.9287
Epoch 55/100
 - 0s - loss: 0.1866 - acc: 0.9332
Epoch 56/100
 - 0s - loss: 0.1792 - acc: 0.9310
Epoch 57/100
 - 0s - loss: 0.2391 - acc: 0.9020
Epoch 58/100
 - 0s - loss: 0.2080 - acc: 0.9065
Epoch 59/100
 - 0s - loss: 0.1801 - acc: 0.9332
Epoch 60/100
 - 0s - loss: 0.1721 - acc: 0.9310
Epoch 61/100
 - 0s - loss: 0.2136 - acc: 0.9198
Epoch 62/100
 - 0s - loss: 0.1925 - acc: 0.9131
Epoch 63/100
 - 0s - loss: 0.1802 - acc: 0.9220
Epoch 64/100
 - 0s - loss: 0.1631 - acc: 0.9332
Epoch 65/100
 - 0s - loss: 0.1582 - acc: 0.9421
Epoch 66/100
 - 0s - loss: 0.2115 - acc: 0.9131
Epoch 67/100
 - 0s - loss: 0.2009 - acc: 0.9109
Epoch 68/100
 - 0s - loss: 0.1658 - acc: 0.9421
Epoch 69/100
 - 0s - loss: 0.1506 - acc: 0.9532
Epoch 70/100
 - 0s - loss: 0.1469 - acc: 0.9465
Epoch 71/100
 - 0s - loss: 0.1643 - acc: 0.9421
Epoch 72/100
 - 0s - loss: 0.1623 - acc: 0.9332
Epoch 73/100
 - 0s - loss: 0.1482 - acc: 0.9488
Epoch 74/100
 - 0s - loss: 0.1404 - acc: 0.9577
Epoch 75/100
 - 0s - loss: 0.1371 - acc: 0.9510
Epoch 76/100
 - 0s - loss: 0.1391 - acc: 0.9532
Epoch 77/100
 - 0s - loss: 0.1327 - acc: 0.9577
Epoch 78/100
 - 0s - loss: 0.1303 - acc: 0.9599
Epoch 79/100
 - 0s - loss: 0.1277 - acc: 0.9555
Epoch 80/100
 - 0s - loss: 0.1222 - acc: 0.9644
Epoch 81/100
 - 0s - loss: 0.1414 - acc: 0.9443
Epoch 82/100
 - 0s - loss: 0.1377 - acc: 0.9532
Epoch 83/100
 - 0s - loss: 0.1253 - acc: 0.9555
Epoch 84/100
 - 0s - loss: 0.1291 - acc: 0.9577
Epoch 85/100
 - 0s - loss: 0.1228 - acc: 0.9577
Epoch 86/100
 - 0s - loss: 0.1144 - acc: 0.9644
Epoch 87/100
 - 0s - loss: 0.1128 - acc: 0.9666
Epoch 88/100
 - 0s - loss: 0.1091 - acc: 0.9644
Epoch 89/100
 - 0s - loss: 0.1069 - acc: 0.9644
Epoch 90/100
 - 0s - loss: 0.1040 - acc: 0.9644
Epoch 91/100
 - 0s - loss: 0.1492 - acc: 0.9465
Epoch 92/100
 - 0s - loss: 0.1561 - acc: 0.9421
Epoch 93/100
 - 0s - loss: 0.1371 - acc: 0.9354
Epoch 94/100
 - 0s - loss: 0.1109 - acc: 0.9710
Epoch 95/100
 - 0s - loss: 0.1032 - acc: 0.9755
Epoch 96/100
 - 0s - loss: 0.1001 - acc: 0.9666
Epoch 97/100
 - 0s - loss: 0.0970 - acc: 0.9688
Epoch 98/100
 - 0s - loss: 0.0959 - acc: 0.9733
Epoch 99/100
 - 0s - loss: 0.0943 - acc: 0.9733
Epoch 100/100
 - 0s - loss: 0.0925 - acc: 0.9800

In [42]:
model1_loss, model1_accuracy = model1.evaluate(X1_test_scaled, y1_test_categorical, verbose=2)
print(f"Normal Neural Network with data - Loss: {model1_loss}, Accuracy: {model1_accuracy}")

model2_loss, model2_accuracy = model2.evaluate(X2_test_scaled, y2_test_categorical, verbose=2)
print(f"Normal Neural Network with/out data - Loss: {model2_loss}, Accuracy: {model2_accuracy}")

Normal Neural Network with data - Loss: 0.7917883899304774, Accuracy: 0.8181818158595593
Normal Neural Network with/out data - Loss: 0.6474228151639303, Accuracy: 0.8133333365122477

In [43]:
model1.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_31 (Dense)             (None, 100)               1200
_________________________________________________________________
dense_32 (Dense)             (None, 100)               10100
_________________________________________________________________
dense_33 (Dense)             (None, 2)                 202
=================================================================
Total params: 11,502
Trainable params: 11,502
Non-trainable params: 0
_________________________________________________________________

In [44]:
model2.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_34 (Dense)             (None, 100)               1200
_________________________________________________________________
dense_35 (Dense)             (None, 100)               10100
_________________________________________________________________
dense_36 (Dense)             (None, 2)                 202
=================================================================
Total params: 11,502
Trainable params: 11,502
Non-trainable params: 0
_________________________________________________________________